# Site settings
title: Greg Dalziel
email: greg.dalziel@gmail.com
author: Greg Dalziel 
description: "Tokyo-based researcher"
baseurl: ""
url: "http://gregdl.github.io"
google_analytics: UA-55036154-1
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
sass: 
  compressed: true

